"""Dataset Lab: local, immutable multimodal dataset preparation."""

from .errors import DatasetLabError, JobError, RecipeError, SchemaError, SourceError, VersionError
from .failure_mining import (
    FAILURE_SELECTION_MODES,
    FailureMiningBuilder,
    FailureMiningCandidate,
    FailureMiningPreview,
    FailureMiningSelector,
    build_failure_mined_version,
    exclusions_hash,
    normalize_exclusions,
    preview_failure_mining,
)
from .comparison import (
    DatasetVersionComparator,
    DatasetVersionComparison,
    compare_dataset_versions,
)
from .identity import RecordIdentity
from .jobs import DatasetJob, JobContext, SerialJobManager
from .integrations import (
    configured_judge,
    configured_semantic_similarity,
    configured_teacher,
    configured_verifier,
)
from .models import (
    CanonicalKind,
    CanonicalSchema,
    adapt_record,
    infer_schema,
    schema_info,
    validate_record,
)
from .profiling import audio_profile, image_profile, profile_records, text_profile
from .recipe import (
    Recipe,
    RecipeContext,
    RecipeResult,
    RecipeRunner,
    RecipeStep,
    SUPPORTED_STEPS,
    validate_recipe,
)
from .review_builds import REVIEW_BUILD_MODES, ReviewDatasetBuilder, ReviewDatasetBuildPreview
from .service import (
    DatasetLab,
    DatasetLabService,
    DatasetSource,
    PreviewPage,
    inherit_dataset_version_exposures,
    record_failure_mining_exposures,
)
from .sources import (
    AssetFingerprint,
    SourceSnapshot,
    SourceSpec,
    fingerprint_assets,
    fingerprint_path,
    load_source,
    verify_snapshot,
)
from .storage import DatasetVersion, VersionStore
from .training_artifacts import (
    DATASET_BINDING_ROLES,
    SUPPORTED_TRAINING_ARTIFACT_FORMAT_VERSIONS,
    TRAINER_DATASET_ADAPTERS,
    TRAINING_ARTIFACT_FORMAT_VERSION,
    DatasetBinding,
    TrainerDatasetAdapter,
    TrainerDatasetAdapterRegistry,
    TrainingArtifactRenderer,
    TrainingDatasetArtifact,
    default_trainer_dataset_adapters,
)

__all__ = [
    "AssetFingerprint",
    "CanonicalKind",
    "CanonicalSchema",
    "DATASET_BINDING_ROLES",
    "DatasetBinding",
    "DatasetJob",
    "DatasetLab",
    "FAILURE_SELECTION_MODES",
    "DatasetLabError",
    "DatasetLabService",
    "DatasetSource",
    "DatasetVersion",
    "JobContext",
    "DatasetVersionComparator",
    "DatasetVersionComparison",
    "JobError",
    "PreviewPage",
    "FailureMiningBuilder",
    "FailureMiningCandidate",
    "FailureMiningPreview",
    "FailureMiningSelector",
    "Recipe",
    "RecipeContext",
    "RecipeError",
    "RecipeResult",
    "RecordIdentity",
    "REVIEW_BUILD_MODES",
    "ReviewDatasetBuilder",
    "ReviewDatasetBuildPreview",
    "RecipeRunner",
    "RecipeStep",
    "SUPPORTED_STEPS",
    "SchemaError",
    "SerialJobManager",
    "SourceError",
    "SourceSnapshot",
    "SourceSpec",
    "SUPPORTED_TRAINING_ARTIFACT_FORMAT_VERSIONS",
    "TRAINER_DATASET_ADAPTERS",
    "TRAINING_ARTIFACT_FORMAT_VERSION",
    "TrainerDatasetAdapter",
    "TrainerDatasetAdapterRegistry",
    "TrainingArtifactRenderer",
    "TrainingDatasetArtifact",
    "VersionError",
    "VersionStore",
    "adapt_record",
    "audio_profile",
    "fingerprint_assets",
    "fingerprint_path",
    "image_profile",
    "configured_judge",
    "configured_semantic_similarity",
    "configured_teacher",
    "configured_verifier",
    "build_failure_mined_version",
    "compare_dataset_versions",
    "default_trainer_dataset_adapters",
    "exclusions_hash",
    "infer_schema",
    "inherit_dataset_version_exposures",
    "record_failure_mining_exposures",
    "load_source",
    "profile_records",
    "schema_info",
    "text_profile",
    "normalize_exclusions",
    "preview_failure_mining",
    "validate_recipe",
    "validate_record",
    "verify_snapshot",
]
