"""Halo Forge Reward Integrity and Training Signal Studio backend."""

from .metrics import (
    IntegrityEvidence,
    RewardScale,
    compute_integrity_metrics,
    grouped_percentile_bootstrap,
    kendall_tau,
    normalize_reward,
    spearman_correlation,
)
from .models import (
    Page,
    ResolvedRewardBinding,
    RewardAuditProtocol,
    RewardAuditProtocolRevision,
    RewardIntegrityAudit,
    RewardIntegrityBinding,
    RewardIntegrityComparison,
    RewardIntegrityComparisonPair,
    RewardIntegrityDecision,
    RewardIntegrityMetric,
    RewardIntegrityObservation,
    RewardIntegrityProfile,
    RewardIntegrityProfileRevision,
    RewardIntegritySample,
    RewardSystem,
    RewardSystemAuditor,
    RewardSystemRevision,
    TrainingRecordRef,
    TrainingSignalShard,
    TrainingSignalSnapshot,
)
from .service import PROFILE_DEFAULTS, PROTOCOL_DEFAULTS, RewardIntegrityService
from .runtime import (
    RewardMappedVerifier,
    execute_pinned_audit,
    register_reward_mapped_verifier,
    verifier_input,
)
from .storage import PublishedBundle, RewardIntegrityStorage
from .store import RewardIntegrityStore

__all__ = [
    "IntegrityEvidence",
    "PROFILE_DEFAULTS",
    "PROTOCOL_DEFAULTS",
    "Page",
    "PublishedBundle",
    "ResolvedRewardBinding",
    "RewardAuditProtocol",
    "RewardAuditProtocolRevision",
    "RewardIntegrityAudit",
    "RewardIntegrityBinding",
    "RewardIntegrityComparison",
    "RewardIntegrityComparisonPair",
    "RewardIntegrityDecision",
    "RewardIntegrityMetric",
    "RewardIntegrityObservation",
    "RewardIntegrityProfile",
    "RewardIntegrityProfileRevision",
    "RewardIntegritySample",
    "RewardIntegrityService",
    "RewardIntegrityStorage",
    "RewardIntegrityStore",
    "RewardMappedVerifier",
    "RewardScale",
    "RewardSystem",
    "RewardSystemAuditor",
    "RewardSystemRevision",
    "TrainingRecordRef",
    "TrainingSignalShard",
    "TrainingSignalSnapshot",
    "compute_integrity_metrics",
    "execute_pinned_audit",
    "grouped_percentile_bootstrap",
    "kendall_tau",
    "normalize_reward",
    "register_reward_mapped_verifier",
    "spearman_correlation",
    "verifier_input",
]
