import { Link, useNavigate, useParams, useSearch } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, ArrowRight, CheckCircle2, ClipboardCheck, Clock3, Filter, ListChecks, Loader2, Pause, Play, Plus, RefreshCcw, Search, ShieldAlert } from "lucide-react";
import { useEffect, useState } from "react";
import { Topbar } from "@/components/shell";
import { DataSectionTabs } from "@/components/data/data-section-tabs";
import { ReviewProposal } from "@/components/review/review-proposal";
import { ReviewItemDesk } from "@/components/review/review-item-desk";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { api, type ReviewItem, type ReviewQueue, type ReviewQueueStatistics, type ReviewQueueSummary } from "@/lib/api";
import { cn } from "@/lib/utils";

type ReviewSearch = { new?: string; source?: string; sourceRef?: string; baseRef?: string; item?: string; status?: string; q?: string; page?: number; pass?: number };

export function ReviewStudioHome() {
  const navigate = useNavigate();
  const search = useSearch({ from: "/datasets/review" }) as ReviewSearch;
  const [proposalOpen, setProposalOpen] = useState(search.new === "1");
  const [query, setQuery] = useState(search.q || "");
  const [queueOffset, setQueueOffset] = useState(Math.max(0, ((search.page || 1) - 1) * 50));
  const queues = useQuery({ queryKey: ["review-queue-summaries", query, queueOffset], queryFn: () => api.reviewQueueSummaries({ q: query || undefined, limit: 50, offset: queueOffset }), refetchInterval: 20_000 });
  const visible = queues.data?.items ?? [];
  const statistics = new Map(visible.map((queue) => [queue.id, queue.statistics]));
  const active = visible.filter((queue) => queue.status === "active").length;
  const conflicts = visible.reduce((sum, item) => sum + Number(item.statistics?.conflicts ?? 0), 0);

  useEffect(() => { if (search.new === "1") setProposalOpen(true); }, [search.new]);

  return <div className="flex h-full min-h-0 flex-col">
    <Topbar eyebrow="Data · Review" title="Review Studio" subtitle="Acquire evidence, make human decisions, and publish traceable labels without leaving Dataset Lab." actions={<Button variant="primary" size="sm" onClick={() => setProposalOpen(true)}><Plus />New review queue</Button>} />
    <DataSectionTabs />
    <div className="flex min-h-0 flex-1 flex-col lg:flex-row">
      <QueueRail queues={visible} statistics={statistics} query={query} onQuery={(value) => { setQuery(value); setQueueOffset(0); navigate({ to: "/datasets/review", search: { ...search, q: value || undefined, page: undefined }, replace: true }); }} loading={queues.isLoading} onRefresh={() => queues.refetch()} total={queues.data?.total ?? visible.length} offset={queueOffset} onOffset={(offset) => { setQueueOffset(offset); navigate({ to: "/datasets/review", search: { ...search, q: query || undefined, page: Math.floor(offset / 50) + 1 }, replace: true }); }} />
      {proposalOpen ? <ReviewProposal initialSource={search.source} initialSourceRef={search.sourceRef} initialBaseRef={search.baseRef} onClose={() => { setProposalOpen(false); navigate({ to: "/datasets/review", search: { ...search, new: undefined, source: undefined, sourceRef: undefined, baseRef: undefined }, replace: true }); }} onCreated={(queueId) => navigate({ to: "/datasets/review/$queueId", params: { queueId }, search: { item: undefined, status: undefined, q: undefined, page: undefined, pass: undefined } })} /> : <ReviewOverview queues={visible} stats={statistics} active={active} conflicts={conflicts} onNew={() => setProposalOpen(true)} />}
    </div>
  </div>;
}

export function ReviewQueueWorkspace() {
  const { queueId } = useParams({ from: "/datasets/review/$queueId" });
  const navigate = useNavigate();
  const search = useSearch({ from: "/datasets/review" }) as ReviewSearch;
  const queryClient = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(search.item || null);
  const [filter, setFilter] = useState(search.status || "all");
  const [query, setQuery] = useState(search.q || "");
  const [itemOffset, setItemOffset] = useState(Math.max(0, ((search.page || 1) - 1) * 100));
  const queue = useQuery({ queryKey: ["review-queue", queueId], queryFn: () => api.reviewQueue(queueId), refetchInterval: 15_000 });
  const statistics = useQuery({ queryKey: ["review-queue-statistics", queueId], queryFn: () => api.reviewQueueStatistics(queueId), refetchInterval: 15_000 });
  const items = useQuery({ queryKey: ["review-queue-items", queueId, filter, query, itemOffset, queue.data?.current_pass], queryFn: () => api.reviewQueueItems(queueId, { status: filter === "all" ? undefined : filter, q: query || undefined, passNumber: queue.data?.current_pass, limit: 100, offset: itemOffset }), enabled: Boolean(queue.data), refetchInterval: 15_000 });
  const schema = useQuery({ queryKey: ["annotation-schema-revision", queue.data?.schema_revision_id], queryFn: () => api.annotationSchemaRevision(queue.data!.schema_revision_id), enabled: Boolean(queue.data?.schema_revision_id) });
  const state = useMutation({ mutationFn: ({ action, reason }: { action: "pause" | "resume" | "archive" | "start-second-pass"; reason?: string }) => api.updateReviewQueueState(queueId, action, reason), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["review-queue", queueId] }); queryClient.invalidateQueries({ queryKey: ["review-queue-items", queueId] }); } });
  const visibleItems = items.data?.items ?? [];

  useEffect(() => {
    if (!visibleItems.length) { if (!search.item) setSelectedId(null); return; }
    if (!selectedId) {
      const next = (visibleItems.find((item) => !["resolved", "excluded"].includes(item.status)) ?? visibleItems[0]).id;
      setSelectedId(next);
      navigate({ to: "/datasets/review/$queueId", params: { queueId }, search: { ...search, item: next, status: filter === "all" ? undefined : filter, q: query || undefined, page: Math.floor(itemOffset / 100) + 1, pass: queue.data?.current_pass }, replace: true });
    }
  }, [selectedId, visibleItems]);

  const selected = useQuery({ queryKey: ["review-item", selectedId], queryFn: () => api.reviewItem(selectedId!), enabled: Boolean(selectedId) });
  const neighbors = useQuery({ queryKey: ["review-item-neighbors", selectedId, filter, query, queue.data?.current_pass], queryFn: () => api.reviewItemNeighbors(selectedId!, { status: filter === "all" ? undefined : filter, q: query || undefined, passNumber: queue.data?.current_pass }), enabled: Boolean(selectedId && queue.data), retry: false });
  const canStartSecond = queue.data?.policy.mode === "two_pass" && queue.data.current_pass === 1 && Number(statistics.data?.status_counts?.pass1_complete ?? 0) + Number(statistics.data?.excluded ?? 0) >= Number(statistics.data?.total ?? Infinity);

  const selectItem = (id: string | null) => { if (!id) return; setSelectedId(id); const position = neighbors.data?.item_id === selectedId ? neighbors.data.position + (id === neighbors.data.next_id ? 1 : id === neighbors.data.previous_id ? -1 : 0) : itemOffset; const nextOffset = Math.max(0, Math.floor(Math.max(0, position) / 100) * 100); if (nextOffset !== itemOffset) setItemOffset(nextOffset); navigate({ to: "/datasets/review/$queueId", params: { queueId }, search: { ...search, item: id, status: filter === "all" ? undefined : filter, q: query || undefined, page: Math.floor(nextOffset / 100) + 1, pass: queue.data?.current_pass }, replace: true }); };
  const move = (delta: number) => selectItem(delta < 0 ? neighbors.data?.previous_id ?? null : neighbors.data?.next_id ?? null);

  if (queue.isLoading || items.isLoading || schema.isLoading) return <ReviewLoading />;
  if (queue.isError || !queue.data || schema.isError || !schema.data) return <ReviewError message={queue.error?.message || schema.error?.message || "Review queue is unavailable."} onBack={() => navigate({ to: "/datasets/review", search: { new: undefined, source: undefined, sourceRef: undefined } })} />;

  return <div className="flex h-full min-h-0 flex-col">
    <Topbar eyebrow={`Data · Review · Pass ${queue.data.current_pass}`} title={queue.data.name} subtitle={`${statistics.data?.resolved ?? 0} of ${statistics.data?.total ?? items.data?.total ?? 0} resolved · ${queue.data.policy.mode === "two_pass" ? "independent two-pass" : "single-pass"} review`} actions={<div className="flex items-center gap-1">{canStartSecond ? <Button size="sm" variant="primary" onClick={() => state.mutate({ action: "start-second-pass" })}><Play />Start second pass</Button> : null}{queue.data.status === "active" ? <Button size="sm" variant="ghost" onClick={() => state.mutate({ action: "pause", reason: "Paused from Review Studio" })}><Pause />Pause</Button> : queue.data.status === "paused" ? <Button size="sm" onClick={() => state.mutate({ action: "resume" })}><Play />Resume</Button> : null}<Button size="icon" variant="ghost" aria-label="Archive queue" onClick={() => state.mutate({ action: "archive", reason: "Archived from Review Studio" })}><Archive /></Button></div>} />
    <DataSectionTabs />
    <div className="flex min-h-0 flex-1 flex-col lg:flex-row">
      <ItemRail queue={queue.data} statistics={statistics.data} items={visibleItems} selectedId={selectedId} query={query} onQuery={(value) => { setQuery(value); setItemOffset(0); navigate({ to: "/datasets/review/$queueId", params: { queueId }, search: { ...search, item: undefined, q: value || undefined, status: filter === "all" ? undefined : filter, page: 1, pass: queue.data.current_pass }, replace: true }); }} filter={filter} onFilter={(value) => { setFilter(value); setItemOffset(0); setSelectedId(null); navigate({ to: "/datasets/review/$queueId", params: { queueId }, search: { ...search, item: undefined, status: value === "all" ? undefined : value, q: query || undefined, page: 1, pass: queue.data.current_pass }, replace: true }); }} onSelect={selectItem} total={items.data?.total ?? 0} offset={itemOffset} onOffset={(offset) => { setItemOffset(offset); setSelectedId(null); navigate({ to: "/datasets/review/$queueId", params: { queueId }, search: { ...search, item: undefined, status: filter === "all" ? undefined : filter, q: query || undefined, page: Math.floor(offset / 100) + 1, pass: queue.data.current_pass }, replace: true }); }} />
      {selected.data ? <ReviewItemDesk key={`${selected.data.id}:${queue.data.current_pass}`} queue={queue.data} item={selected.data} schema={schema.data} position={neighbors.data?.position ?? selected.data.ordinal} total={neighbors.data?.total ?? items.data?.total ?? 0} onPrevious={() => move(-1)} onNext={() => move(1)} /> : selected.isLoading ? <div className="grid flex-1 place-items-center text-[10px] text-fg-disabled"><Loader2 className="mb-2 animate-spin" />Loading item…</div> : <ReviewComplete queue={queue.data} statistics={statistics.data} canStartSecond={canStartSecond} onStartSecond={() => state.mutate({ action: "start-second-pass" })} />}
    </div>
  </div>;
}

function QueueRail({ queues, statistics, query, onQuery, loading, onRefresh, total, offset, onOffset }: { queues: ReviewQueueSummary[]; statistics: Map<string, ReviewQueueStatistics | undefined>; query: string; onQuery: (value: string) => void; loading: boolean; onRefresh: () => void; total: number; offset: number; onOffset: (offset: number) => void }) {
  return <aside className="flex max-h-72 w-full shrink-0 flex-col border-b border-border bg-bg-subtle/35 lg:max-h-none lg:w-[310px] lg:border-b-0 lg:border-r" aria-label="Review queues">
    <div className="flex items-center gap-2 border-b border-border-subtle p-3"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-fg-disabled" /><Input aria-label="Search review queues" value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search review queues" className="pl-8" /></div><Button size="icon" variant="ghost" onClick={onRefresh} aria-label="Refresh review queues"><RefreshCcw /></Button></div>
    <div className="min-h-0 flex-1 overflow-y-auto p-2">{loading ? <div className="py-10 text-center text-[10px] text-fg-disabled">Loading review queues…</div> : queues.length ? queues.map((queue) => <QueueLink key={queue.id} queue={queue} statistics={statistics.get(queue.id)} />) : <div className="px-3 py-10 text-center"><ListChecks className="mx-auto h-5 w-5 text-fg-disabled" /><p className="mt-2 text-[10px] text-fg-subtle">No review queues match this view.</p></div>}</div><div className="flex items-center justify-between border-t border-border-subtle px-2 py-2"><span className="font-mono text-[8.5px] text-fg-disabled">{total ? `${offset + 1}–${Math.min(total, offset + 50)} of ${total}` : "0 queues"}</span><div className="flex gap-1"><Button size="sm" variant="ghost" disabled={offset === 0} onClick={() => onOffset(Math.max(0, offset - 50))}>Prev</Button><Button size="sm" variant="ghost" disabled={offset + 50 >= total} onClick={() => onOffset(offset + 50)}>Next</Button></div></div>
  </aside>;
}

function QueueLink({ queue, statistics }: { queue: ReviewQueue; statistics?: ReviewQueueStatistics }) {
  const total = Number(statistics?.total ?? 0); const resolved = Number(statistics?.resolved ?? 0); const progress = total ? Math.round(resolved / total * 100) : 0;
  return <Link to="/datasets/review/$queueId" params={{ queueId: queue.id }} className="group mb-1 block rounded-md border border-transparent px-3 py-3 transition-colors hover:border-border hover:bg-surface/60">
    <div className="flex items-start justify-between gap-2"><div className="min-w-0"><div className="truncate text-[11.5px] font-medium text-fg group-hover:text-accent">{queue.name}</div><div className="mt-0.5 flex items-center gap-2 text-[9px] text-fg-disabled"><span>{humanize(queue.status)}</span><span>pass {queue.current_pass}</span>{statistics?.conflicts ? <span className="text-warning">{statistics.conflicts} conflicts</span> : null}</div></div><ArrowRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-fg-disabled opacity-0 transition-opacity group-hover:opacity-100" /></div>
    <div className="mt-2 h-1 overflow-hidden rounded-full bg-border"><div className="h-full rounded-full bg-accent transition-[width]" style={{ width: `${progress}%` }} /></div><div className="mt-1 flex justify-between font-mono text-[8.5px] text-fg-disabled"><span>{resolved}/{total || "—"}</span><span>{progress}%</span></div>
  </Link>;
}

function ReviewOverview({ queues, stats, active, conflicts, onNew }: { queues: ReviewQueue[]; stats: Map<string, ReviewQueueStatistics | undefined>; active: number; conflicts: number; onNew: () => void }) {
  const resolved = [...stats.values()].reduce((sum, value) => sum + Number(value?.resolved ?? 0), 0);
  return <main className="min-w-0 flex-1 overflow-y-auto p-5 lg:p-8"><div className="mx-auto max-w-5xl"><section className="grid gap-6 border-b border-border pb-7 lg:grid-cols-[1fr_340px] lg:items-end"><div><div className="font-mono text-[10px] uppercase tracking-[0.15em] text-accent">Human feedback workspace</div><h2 className="mt-2 max-w-2xl text-2xl font-semibold tracking-tight text-fg">Keep review focused on one consequential decision at a time.</h2><p className="mt-2 max-w-2xl text-[11px] leading-5 text-fg-subtle">Build deterministic candidate sets from evaluations, datasets, runs, or local records. Review with a pinned rubric, then hand verified labels back to Dataset Lab.</p><Button className="mt-4" size="sm" variant="primary" onClick={onNew}><Plus />Propose a review queue</Button></div><div className="grid grid-cols-3 gap-px overflow-hidden rounded-lg border border-border bg-border"><OverviewStat label="Active" value={active} icon={<Clock3 />} /><OverviewStat label="Resolved" value={resolved} icon={<CheckCircle2 />} /><OverviewStat label="Conflicts" value={conflicts} icon={<ShieldAlert />} /></div></section>
    <section className="py-6"><div className="mb-3 flex items-center justify-between"><div><h3 className="text-sm font-semibold text-fg">Recent queues</h3><p className="mt-0.5 text-[10px] text-fg-subtle">Continue the next unresolved decision, or inspect a completed label set.</p></div><span className="font-mono text-[9px] text-fg-disabled">{queues.length} total</span></div>{queues.length ? <div className="overflow-hidden rounded-lg border border-border"><div className="divide-y divide-border-subtle">{queues.slice(0, 8).map((queue) => { const value = stats.get(queue.id); const total = Number(value?.total ?? 0); const resolvedCount = Number(value?.resolved ?? 0); return <Link key={queue.id} to="/datasets/review/$queueId" params={{ queueId: queue.id }} className="grid items-center gap-3 bg-surface/25 px-4 py-3 transition-colors hover:bg-surface/65 sm:grid-cols-[minmax(0,1fr)_120px_140px_24px]"><div className="min-w-0"><div className="truncate text-[11.5px] font-medium text-fg">{queue.name}</div><div className="mt-0.5 truncate font-mono text-[8.5px] text-fg-disabled">{queue.id}</div></div><Badge tone={queue.status === "active" ? "accent" : queue.status === "completed" ? "success" : "neutral"} size="sm">{humanize(queue.status)}</Badge><div><div className="flex justify-between font-mono text-[8.5px] text-fg-disabled"><span>{resolvedCount}/{total || "—"}</span><span>{total ? Math.round(resolvedCount / total * 100) : 0}%</span></div><div className="mt-1 h-1 overflow-hidden rounded-full bg-border"><div className="h-full bg-accent" style={{ width: `${total ? resolvedCount / total * 100 : 0}%` }} /></div></div><ArrowRight className="h-3.5 w-3.5 text-fg-disabled" /></Link>; })}</div></div> : <div className="rounded-lg border border-dashed border-border px-5 py-12 text-center"><ClipboardCheck className="mx-auto h-6 w-6 text-fg-disabled" /><h3 className="mt-3 text-sm font-medium text-fg">No review queues yet</h3><p className="mx-auto mt-1 max-w-sm text-[10.5px] leading-5 text-fg-subtle">Start from a completed evaluation, a dataset version, or imported interaction records.</p><Button className="mt-4" size="sm" onClick={onNew}>Create the first queue</Button></div>}</section></div></main>;
}

function ItemRail({ queue, statistics, items, selectedId, query, onQuery, filter, onFilter, onSelect, total, offset, onOffset }: { queue: ReviewQueue; statistics?: ReviewQueueStatistics; items: ReviewItem[]; selectedId: string | null; query: string; onQuery: (value: string) => void; filter: string; onFilter: (value: string) => void; onSelect: (value: string) => void; total: number; offset: number; onOffset: (offset: number) => void }) {
  const statuses = Object.keys(statistics?.status_counts ?? {});
  return <aside className="flex max-h-52 w-full shrink-0 flex-col border-b border-border bg-bg-subtle/35 lg:max-h-none lg:w-64 lg:border-b-0 lg:border-r" aria-label="Items in review queue"><div className="border-b border-border-subtle p-3"><Link to="/datasets/review" search={{ new: undefined, source: undefined, sourceRef: undefined, baseRef: undefined, item: undefined, status: undefined, q: undefined, page: undefined, pass: undefined }} className="text-[9.5px] text-fg-subtle hover:text-accent">← All review queues</Link><div className="mt-2 flex items-center gap-2"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-fg-disabled" /><Input aria-label="Search review items" value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Find item" className="pl-8" /></div><div className="relative"><Filter className="pointer-events-none absolute left-2 top-1/2 h-3 w-3 -translate-y-1/2 text-fg-disabled" /><select aria-label="Filter review item status" value={filter} onChange={(event) => onFilter(event.target.value)} className="h-8 w-9 appearance-none rounded-md border border-border bg-surface text-transparent outline-none focus:border-accent"><option value="all">All statuses</option>{statuses.map((status) => <option key={status} value={status}>{humanize(status)}</option>)}</select></div></div></div><div className="min-h-0 flex-1 overflow-y-auto p-2">{items.map((item) => <button key={item.id} type="button" onClick={() => onSelect(item.id)} className={cn("mb-1 flex w-full items-start gap-2 rounded-md border px-2.5 py-2 text-left transition-colors", selectedId === item.id ? "border-accent/45 bg-accent/7" : "border-transparent hover:border-border hover:bg-surface/55")}><StatusMark status={item.status} /><span className="min-w-0 flex-1"><span className="block truncate text-[10.5px] font-medium text-fg">{recordSummary(item)}</span><span className="mt-0.5 block truncate font-mono text-[8px] text-fg-disabled">{item.record_id || item.id}</span></span><span className="font-mono text-[8px] text-fg-disabled">{item.ordinal + 1}</span></button>)}</div><div className="border-t border-border-subtle px-2 py-2"><div className="flex items-center justify-between font-mono text-[8.5px] text-fg-disabled"><span>{total ? `${offset + 1}–${Math.min(total, offset + 100)} of ${total}` : "0 items"}</span><span>pass {queue.current_pass}</span></div><div className="mt-1 flex justify-end gap-1"><Button size="sm" variant="ghost" disabled={offset === 0} onClick={() => onOffset(Math.max(0, offset - 100))}>Prev</Button><Button size="sm" variant="ghost" disabled={offset + 100 >= total} onClick={() => onOffset(offset + 100)}>Next</Button></div></div></aside>;
}

function StatusMark({ status }: { status: string }) { return <span className={cn("mt-1 h-2 w-2 shrink-0 rounded-full", status === "resolved" ? "bg-success" : status === "conflict" ? "bg-warning" : status === "excluded" ? "bg-danger" : status === "flagged" ? "bg-info" : "border border-border-strong")} title={humanize(status)} />; }
function OverviewStat({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <div className="bg-surface/55 px-3 py-4"><span className="text-accent [&_svg]:h-3.5 [&_svg]:w-3.5">{icon}</span><div className="mt-3 font-mono text-xl text-fg">{value}</div><div className="mt-0.5 text-[8.5px] uppercase tracking-wider text-fg-disabled">{label}</div></div>; }
function ReviewLoading() { return <div className="grid min-h-screen place-items-center bg-bg text-[10px] text-fg-disabled"><div className="text-center"><Loader2 className="mx-auto mb-2 h-5 w-5 animate-spin text-accent" />Opening review queue…</div></div>; }
function ReviewError({ message, onBack }: { message: string; onBack: () => void }) { return <div className="grid min-h-screen place-items-center bg-bg p-5"><div className="max-w-md rounded-lg border border-danger/25 bg-danger/5 p-5 text-center"><ShieldAlert className="mx-auto h-6 w-6 text-danger" /><h1 className="mt-3 text-sm font-semibold text-fg">Review queue unavailable</h1><p className="mt-1 text-[10.5px] leading-5 text-fg-subtle">{message}</p><Button className="mt-4" size="sm" onClick={onBack}>Back to Review Studio</Button></div></div>; }
function ReviewComplete({ queue, statistics, canStartSecond, onStartSecond }: { queue: ReviewQueue; statistics?: ReviewQueueStatistics; canStartSecond: boolean; onStartSecond: () => void }) { return <div className="grid min-h-0 flex-1 place-items-center p-5"><div className="max-w-md text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-success" /><h2 className="mt-3 text-lg font-semibold text-fg">This view is complete</h2><p className="mt-1 text-[10.5px] leading-5 text-fg-subtle">{statistics?.resolved ?? 0} decisions are resolved for pass {queue.current_pass}. {canStartSecond ? "The independent second pass is ready." : "Adjust the item filter to inspect earlier decisions."}</p>{canStartSecond ? <Button className="mt-4" size="sm" variant="primary" onClick={onStartSecond}><Play />Start second pass</Button> : null}</div></div>; }
function recordSummary(item: ReviewItem) { const record = item.record ?? {}; const value = record.title ?? record.prompt ?? record.input ?? record.question ?? record.transcript ?? (Array.isArray(record.messages) ? (record.messages[0] as Record<string, unknown>)?.content : null); return value ? String(value).slice(0, 80) : `Item ${item.ordinal + 1}`; }
function humanize(value: string) { return value.replace(/[_-]/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
