"""Guided own-data training contracts and services."""

from .imports import (
    DatasetImportManager,
    InsufficientDiskCapacityError,
    safe_relative_path,
)
from .inspection import (
    IMPORT_ADAPTER_VERSION,
    fingerprint_path,
    infer_schema_candidates,
    inspect_path,
)
from .mapping import apply_mapping, build_preparation_plan, evaluate_expression, preview_mapping
from .guidance import (
    advise_scenarios,
    build_readiness_report,
    guided_example_descriptors,
    semantic_previews,
)
from .models import (
    CorpusPackingPlan,
    CorpusProfile,
    CorpusTrainingConfig,
    DatasetImportFile,
    DatasetImportSession,
    DatasetPreparationPlan,
    DatasetReadiness,
    DatasetReadinessReport,
    DatasetSourceInspection,
    FieldMappingExpression,
    FieldMappingPlan,
    GuidedExampleDescriptor,
    InterfaceCapabilityDescriptor,
    MappingPreview,
    RemediationAction,
    ScenarioAdviceRequest,
    ScenarioAdviceResult,
    SchemaCandidate,
    SemanticRecordPreview,
    TrainingScenarioDescriptor,
    TrainingScenarioExample,
)
from .registry import TRAINING_SCENARIOS, TrainingScenarioRegistry, interface_capabilities
from .service import GuidedOwnDataService, GuidedRegistrationConflict

__all__ = [
    "CorpusPackingPlan",
    "CorpusProfile",
    "CorpusTrainingConfig",
    "DatasetImportFile",
    "DatasetImportManager",
    "DatasetImportSession",
    "DatasetPreparationPlan",
    "DatasetReadiness",
    "DatasetReadinessReport",
    "DatasetSourceInspection",
    "FieldMappingExpression",
    "FieldMappingPlan",
    "GuidedExampleDescriptor",
    "GuidedOwnDataService",
    "GuidedRegistrationConflict",
    "IMPORT_ADAPTER_VERSION",
    "InterfaceCapabilityDescriptor",
    "InsufficientDiskCapacityError",
    "MappingPreview",
    "RemediationAction",
    "ScenarioAdviceRequest",
    "ScenarioAdviceResult",
    "SchemaCandidate",
    "SemanticRecordPreview",
    "TRAINING_SCENARIOS",
    "TrainingScenarioDescriptor",
    "TrainingScenarioExample",
    "TrainingScenarioRegistry",
    "advise_scenarios",
    "apply_mapping",
    "build_readiness_report",
    "build_preparation_plan",
    "evaluate_expression",
    "fingerprint_path",
    "guided_example_descriptors",
    "infer_schema_candidates",
    "inspect_path",
    "interface_capabilities",
    "preview_mapping",
    "safe_relative_path",
    "semantic_previews",
]
